System Check Script #6: Radio 
PyCubed-Mini/flight_software pull request #127
Opened 2022-07-26 21:42 UTC by yashika-batra

Radio Test: clean up + style and documentation fixes

2022-07-29 17:03 UTC, thetazero requested changes
I'm not sure if we want to use this code, I've wrote a test script that does something a little more advanced for the radio, and is compatible with my new updates as well.

We may want to hold off on this one for now, and have me port my work into the check script.

2022-07-29 17:03 UTC, thetazero commented on state_machine/applications/system-check/tests/radio_test.py
> +    if test_type == "Both":
split these test types into separate functions please

2022-07-29 17:03 UTC, thetazero commented on state_machine/applications/system-check/tests/radio_test.py
> +            cubesat.radio.send(send_text, keep_listening=True)
pretty sure you can just do send_with_ack

2022-07-29 17:03 UTC, thetazero commented on state_machine/applications/system-check/tests/radio_test.py
> +            receive_val_string = ("Succeeded in receiving message" +
f string

2022-08-03 08:24 UTC, yashika-batra commented
Leaving this as is for now, since we'll most likely be using Losha's radio test as part of the check script.

2022-11-18 20:44 UTC, closed without merging