Deployment state [DRAFT]
PyCubed-Mini/flight_software pull request #221
Opened 2022-10-12 21:10 UTC by thetazero

- Added ability to toggle randomization of voltage readings (around low bat threshold) for emulation mode via entering ">>>dv"
- Added deployment state
- Added deployment_manager task
  - If contact established transition to normal mode
  - Otherwise activate burnwire for 15 seconds at default duty cycle
- Added initial state to config.py (application level)
- Added previous state to state machine
- Improved safety state to transition back to previous state
- Renamed f_deploy to f_contact
- Added f_contact to emulation
- Added burn function to emulation
- Added ability to toggle emulated contact flag via ">>>dc"

2022-10-12 21:18 UTC, jbwillis requested changes
This all makes sense to me. A couple typos. One feature I think we need to add is a timer to check if the satellite has been on for a certain amount of time before deploying. Message Zac to see if this is actually necessary.

2022-10-12 21:18 UTC, jbwillis commented on state_machine/applications/flight/Tasks/deployment_manager.py
> +                self.deubg('Uncuccessful burn')
Unsuccessful (spelling error)

2022-10-12 21:18 UTC, jbwillis commented on state_machine/applications/flight/Tasks/deployment_manager.py
> +                self.deubg('Uncuccessful burn')
also `debug`

2022-10-13 00:40 UTC, thetazero commented on state_machine/applications/flight/Tasks/deployment_manager.py
> +                self.deubg('Uncuccessful burn')
thanks, fixed

2022-10-13 00:43 UTC, thetazero commented
@jbwillis Looks like we will probably have to add a delay (about 30 minutes to an hour), this is a feature that I've been meaning to
add to the state machine/tasko anyways so I'll make a separate issue for this.

2022-10-13 01:09 UTC, jbwillis commented
This brings up some interesting operations questions. Like, do we detumble
before deployment?

On Wed, Oct 12, 2022 at 8:43 PM thetazero ***@***.***> wrote:

> @jbwillis <https://github.com/jbwillis> Looks like we will probably have
> to add a delay (about 30 minutes to an hour), this is a feature that I've
> been meaning to
> add to the state machine/tasko anyways so I'll make a separate issue for
> this.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/PyCubed-Mini/flight_software/pull/221#issuecomment-1276887914>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHAS4ZX2SV36L57O6KLZZM3WC5LKVANCNFSM6AAAAAARDVGNQI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-13 13:23 UTC, thetazero commented
That's a very good point. I think detumbling if we are over some angular velocity threshold makes sense.

2022-10-26 18:44 UTC, merged