Add an NVM Access Test for all counters in NVM
PyCubed-Mini/flight_software pull request #229
Opened 2022-11-03 19:47 UTC by yashika-batra

2022-11-03 19:53 UTC, yashika-batra commented
Waiting to merge #227  : Once asyncio/test selection is merged into main, we can merge main with this branch and then merge the NVM access test specific updates.

2022-11-04 13:57 UTC, thetazero requested changes
Really like the direction this is heading in.

Two things are missing however:
- The single bit flags like f_deploy or f_burn.
- Checks to ensure the multi bit flags do not interfere with each other or reference the same region on non volatile memory. You can test this by setting all multi bit flags to their max value, then for each multibit flag change it to 0, and ensure that none of the other multi bit flags were changed.

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/main.py
> +    ("NVM Test", "nvm", tests.nvm_access_test, True)
Comma at the end of this line to keep commits small

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +def verify_bits(counterstr, counter):
This function feels pretty hardcoded, and will break if we change the sizes of our NVM counters.
```python
    def __init__(self,num_bits,register,lowest_bit):
        self.maxval = (1 << num_bits)-1
        self.bit_mask = self.maxval << lowest_bit
        self.lowest_bit=lowest_bit
        self.byte=register
```
Looking at the source code of multiBitFlag we should be able to extract the max value automatically.

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +def incr_logfail_count(cubesat):
This and the following function can just be replaced by their contents:
```python
cubesat.c_logfail += 1
# and 
cubesat.c_logfail = 0
```

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +            counter_access_string += nvm_counters_items[i][0] + ";"
probably want a space after the ";"

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +        # if the counter exists, verify its values
This comment is misleading, we do not verify its values at this point.

2022-11-04 13:57 UTC, thetazero commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +    For each i2c device, print addresses of connected devices
misleading doc string

2022-11-11 23:41 UTC, yashika-batra commented
Thanks for the suggestions! I've added tests for flags, as well as the test you mentioned about counter memory interference. Let me know if there's anything else you have in mind!

2022-11-16 04:06 UTC, jbwillis requested changes

2022-11-16 04:06 UTC, jbwillis commented on state_machine/applications/system-check/tests/nvm_access_test.py
> +            counter_flag_access_string += nvm_flags_items[i][0] + "; "
This is definitely an issue - `i` does not correspond between `nvm_flags_values` and `nvm_flags_items`

2022-11-16 04:06 UTC, jbwillis commented on state_machine/drivers/pycubedmini/lib/logging.py
> +    # rmdir(f"{sd_card_directory}/{folder}")
I don't think this should be part of this PR

2022-11-16 04:06 UTC, jbwillis commented on state_machine/drivers/pycubedmini/lib/pycubed.py
> +        self.f_free1 = 0
what are `f_free1` and `f_free2`?

2022-11-16 04:06 UTC, jbwillis commented on state_machine/drivers/pycubedmini/lib/pycubed.py
> +        self.c_boot += 1  # increment boot count
This should happen immediately after setting `BOOTTIME` (line 113)

2022-11-19 16:15 UTC, jbwillis requested changes

2022-11-19 16:15 UTC, jbwillis commented on state_machine/applications/system-check/main.py
> +    # ("Logging Infrastructure Test", "log", tests.logging_infrastructure_test, True),
delete this line (logging infrastructure...)

2022-11-19 16:15 UTC, jbwillis commented on state_machine/drivers/pycubedmini/lib/pycubed.py
> +        # Define NVM flags
Define -> Reset

2022-11-19 16:15 UTC, jbwillis commented on state_machine/drivers/pycubedmini/lib/pycubed.py
> +        # Define NVM counters
Define -> Reset

2022-11-19 16:15 UTC, jbwillis commented on state_machine/applications/system-check/main.py
> +nvm_reset = input(f"\n\nWould you like to reset non-volatile memory? Select {bold}(y){normal} for yes," +
I'd rather not have this here - I think it belongs in the nvm test file.

When the NVM test runs, all of the NVM registers are changed. Do they get reset at the end of the test?
Let's just have the NVM test reset all of the NVM as it completes.

2022-11-19 16:32 UTC, jbwillis requested changes

2022-11-19 16:32 UTC, jbwillis commented on state_machine/applications/system-check/main.py
> +    ("NVM Test", "nvm", tests.nvm_access_test, True),
Per my comment below about resetting the NVM, I think this should be renamed to "Reset and test NVM"

2022-11-19 16:32 UTC, jbwillis commented on state_machine/applications/system-check/main.py
> +    ("NVM Test", "nvm", tests.nvm_access_test, True),
It should be clear here that the test modifies the NVM

2022-12-01 23:47 UTC, closed without merging