IMU test update [DRAFT]
PyCubed-Mini/flight_software pull request #233
Opened 2022-11-04 15:49 UTC by thetazero

Initial work on the IMU test:

![image](https://user-images.githubusercontent.com/28244551/200018635-71340993-6bc8-42ff-a350-926b94c0d8e1.png)

2022-11-17 02:23 UTC, jbwillis requested changes

2022-11-17 02:23 UTC, jbwillis commented on state_machine/applications/system-check/test_utils.py
> +less_in_magnitude = (
took me a while to figure out what these are (and you've described them to me a bit). At a minimum could you end the name of all of the things that go in the "condition" field of expect() with `_condition`. 

For example:
`less_in_magnitude_condition`

2022-11-21 23:03 UTC, thetazero commented on state_machine/applications/system-check/tests/imu_test.py
> +    dirs = [
good idea

2022-11-21 23:22 UTC, thetazero commented on state_machine/applications/system-check/tests/imu_test.py
> +    await tasko.sleep(wait_time)
doesn't change anything really behavior wise, but switched to time for simplicity.

2022-12-04 22:36 UTC, jbwillis approved these changes

2022-12-04 22:38 UTC, merged