FSK radio library integration
PyCubed-Mini/flight_software pull request #262
Opened 2022-12-04 17:41 UTC by jbwillis

Address #257

2022-12-06 21:46 UTC, jbwillis commented
Successfully tested on hardware.

2022-12-06 22:00 UTC, thetazero requested changes
Should be super easy to make this async compatible, I think it's worth the effort.

2022-12-06 22:00 UTC, thetazero commented on state_machine/drivers/pycubedmini/lib/pycubed_rfm9x_fsk.py
> +            if self.rx_done():
want to add an else tasko.sleep(0.0)

2022-12-07 03:03 UTC, thetazero requested changes
missing await in 2 spots, as far as I can tell

2022-12-07 03:03 UTC, thetazero commented on state_machine/drivers/pycubedmini/lib/pycubed_rfm9x_fsk.py
> +                ack_packet = self.receive(
missing await for receive

2022-12-07 03:03 UTC, thetazero commented on state_machine/drivers/pycubedmini/lib/pycubed_rfm9x_fsk.py
> +            self.send(data, keep_listening=True)
missing await for send

2022-12-09 19:57 UTC, thetazero approved these changes

2022-12-09 21:50 UTC, merged