Logging Infrastructure + Logging and SD Test Updates
PyCubed-Mini/flight_software pull request #281
Opened 2022-12-09 21:03 UTC by yashika-batra

2022-12-09 21:30 UTC, jbwillis requested changes

2022-12-09 21:30 UTC, jbwillis commented on state_machine/applications/system-check/tests/logging_infrastructure_test.py
> +"""
delete header

2022-12-09 21:30 UTC, jbwillis commented on state_machine/applications/system-check/main.py
> +    ("SD Test / Clear Logs", "sd", tests.sd_test, True),
Let's keep the SD test simple - no data deletion

2022-12-09 21:30 UTC, jbwillis commented on state_machine/applications/system-check/tests/sd_test.py
> +    cubesat.clear_logs()
delete

2022-12-09 21:30 UTC, jbwillis commented on state_machine/applications/system-check/tests/sd_test.py
> +    cubesat.clear_logs()
delete

2022-12-10 16:05 UTC, thetazero requested changes
There's a lot of driver code mixing with application level code.

Could you please try and do this with no modifications to the driver.

2023-01-11 15:58 UTC, jbwillis commented
Made obsolete by #347

2023-01-11 15:58 UTC, closed without merging