Uplink enables downlink for 5 minutes
PyCubed-Mini/flight_software pull request #326
Opened 2022-12-29 19:44 UTC by thetazero

2022-12-29 20:37 UTC, jbwillis requested changes

2022-12-29 20:37 UTC, jbwillis commented on state_machine/applications/flight/Tasks/radio.py
> +        tx_before_time = time.time() + TX_UPLINK_ENABLE_TIME
`global tx_before_time`

2022-12-30 17:27 UTC, thetazero commented on state_machine/applications/flight/Tasks/radio.py
> +        tx_before_time = time.time() + TX_UPLINK_ENABLE_TIME
Thanks, fixed now

2023-01-02 14:54 UTC, jbwillis approved these changes

2023-01-02 14:55 UTC, merged