Image Task
PyCubed-Mini/flight_software pull request #383
Opened 2023-07-17 15:02 UTC by tomyyyD

Image task runs every 5 seconds. If 60 seconds have elapsed since the camera was last turned on, it will turn on the camera and initiate getting an image. If the camera is on but hasn't been contacted, the task will check for a byte that the camera will send when it starts up to confirm the connection. If the camera is on and has been contacted, it will take an image, store the image on its SD card and send that image over in 500B packets to the mainboard. Each time the task runs, it will spend a maximum of 2 seconds sending as many packets as it can. When the image is finished the camera will be turned off.

2023-07-17 15:39 UTC, tomyyyD commented
closes #368

2023-07-18 02:36 UTC, thetazero commented on state_machine/applications/flight/Tasks/image_task.py
> +# Transmit "Hello World" beacon
comment here probably wasn't intended

2023-07-18 03:01 UTC, thetazero requested changes
This looks really good, I'm really happy with the design you've chosen. 

Two things to consider (that don't necessarily have to be done in this pr)
1. As it stands this is very hard to run automatic tests on. 
We could improve this by separating the communication protocol, the communication drivers, and the actual task further. 
2. For our GNC code a 2 second outage is really annoying to deal with. We can fix this by making it significantly shorter, or by making the code that loads an image over uart not impose significant outages (I think this is nicer, because then we can load a full image per call)

2023-07-18 20:29 UTC, tomyyyD commented on state_machine/applications/flight/Tasks/image_task.py
> +header_buffer  = bytearray(1)
moved all buffer interactions into a separate camera driver, so hopefully that makes things clearer. I also added comments for what each buffer does.

2023-07-18 20:33 UTC, tomyyyD commented on state_machine/applications/flight/Tasks/image_task.py
> +                # turn off camera to not waste battery as something is wrong
created a few alerts that represent the image task and camera device. camera_available, camera_failed, image_queue_full.

2023-07-18 20:34 UTC, tomyyyD commented on state_machine/applications/flight/Tasks/image_task.py
> +    async def get_packets(self, st):
I'm not entirely familiar with how we are deferring execution. Does making the function async and awaiting its execution not defer execution?

2023-07-18 20:34 UTC, tomyyyD commented on state_machine/applications/flight/Tasks/image_task.py
> +    def get_packet(self) -> bool:
I created a separate camera driver that has the get_packet function

2023-07-20 13:11 UTC, tomyyyD commented
If anyone has thoughts on a better way for the camera driver's `get_packet()` function to return the status of the packet, let me know I'm open to ideas.

2023-07-22 00:58 UTC, thetazero requested changes
Still a little concerned about not having testing for this. 
I think it's fine to merge without given that it's a big effort to bring tests like these up, but lets discuss a plan first to make sure this code is possible to test.

2023-07-22 00:58 UTC, thetazero commented on applications/flight/Tasks/image.py
> +            alerts.clear(self.debug, 'camera_available')
imo we can skip this, the hardware monitor will get to it.

2023-07-22 00:58 UTC, thetazero commented on applications/flight/Tasks/image.py
> +            alerts.clear(self.debug, 'camera_available')
maybe a camera_task alert

2023-07-22 00:58 UTC, thetazero commented on applications/flight/Tasks/hw_monitor.py
> +        alerts.set_value(self.debug, 'camera_available', cubesat.camera is not None and cubesat.sdcard is not None)
probably want to split this into a camera/std card alert. This was we'd know which devices are actually offline (unless we genuinely cannot tell if the camera is available when the sdcard is not)

2023-07-22 00:58 UTC, thetazero commented on drivers/pycubedmini/lib/camera.py
> +        - 5: failed to get packet
I think it'd be more readable if we return constants like `SUCCESS`, `SUCESS_NOT_INTERESTING_IMAGE`, etc... flags are a little difficult to read. Then on the application side we could just compare to these constants.

2023-07-24 20:11 UTC, tomyyyD commented
closes #392

2023-07-26 04:43 UTC, thetazero approved these changes
Looks good

2023-07-27 16:20 UTC, merged